#!/usr/bin/env bash
# Bootstrap the pinned local dependency checkouts under dev/.
#
# dev/ is gitignored on purpose: it is the intermediate, machine-local site
# where Vistalith fixes the SDDK revision it compiles against
# (architecture/DEPENDENCY-MODEL.md — "Local development: sibling checkout,
# direct path dependencies"; "CI/release: pin all SDDK crates to the exact
# same git tag/commit").
#
# The pinned revision lives in scripts/sddk-pin.env and must always be a
# clean, pushed git ref (tag preferred). Re-pin with:
#   scripts/bootstrap-dev.sh --pin <tag-or-commit>
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PIN_ENV="$ROOT/scripts/sddk-pin.env"

SDDK_ORIGIN="https://github.com/Rubentxu/software-development-decision-kernel.git"
# Local sibling checkout used as clone source when available (offline-friendly).
SDDK_LOCAL="${SDDK_LOCAL:-$HOME/Proyectos/agentesIA/sddk-framework}"

if [[ "${1:-}" == "--pin" ]]; then
  REF="${2:?usage: bootstrap-dev.sh --pin <tag-or-commit>}"
  SRC="$SDDK_LOCAL"
  [[ -d "$SRC" ]] || SRC="$SDDK_ORIGIN"
  REV="$(git -C "$SRC" rev-parse "$REF^{commit}")" || {
    echo "error: '$REF' not found in $SRC" >&2; exit 1; }
  DESC="$(git -C "$SRC" describe --tags --exact-match "$REV" 2>/dev/null || echo "$REV")"
  cat > "$PIN_ENV" <<EOF
# SDDK pin — regenerated by scripts/bootstrap-dev.sh --pin <ref>
SDDK_ORIGIN=$SDDK_ORIGIN
SDDK_REF=$DESC
SDDK_COMMIT=$REV
EOF
  echo "pin updated: $DESC ($REV)"
  echo "NOTE: only pins that exist on $SDDK_ORIGIN are valid for CI; verify with: git -C dev/sddk-framework branch -r --contains $REV"
fi

# shellcheck source=sddk-pin.env
source "$PIN_ENV"

if [[ -d "$ROOT/dev/sddk-framework/.git" ]]; then
  echo "dev/sddk-framework already exists"
else
  SRC="$SDDK_LOCAL"
  [[ -d "$SRC/.git" ]] || SRC="$SDDK_ORIGIN"
  echo "cloning $SRC -> dev/sddk-framework"
  git clone --quiet "$SRC" "$ROOT/dev/sddk-framework"
fi

ACTUAL="$(git -C "$ROOT/dev/sddk-framework" rev-parse HEAD)"
if [[ "$ACTUAL" != "$SDDK_COMMIT" ]]; then
  echo "checking out pinned revision $SDDK_COMMIT ($SDDK_REF)"
  git -C "$ROOT/dev/sddk-framework" checkout --quiet --detach "$SDDK_COMMIT"
fi

ACTUAL="$(git -C "$ROOT/dev/sddk-framework" rev-parse HEAD)"
if [[ "$ACTUAL" != "$SDDK_COMMIT" ]]; then
  echo "error: dev/sddk-framework is at $ACTUAL, expected $SDDK_COMMIT" >&2
  exit 1
fi
if [[ -n "$(git -C "$ROOT/dev/sddk-framework" status --porcelain)" ]]; then
  echo "error: dev/sddk-framework working tree is not clean" >&2
  exit 1
fi

echo "SDDK pinned at $SDDK_REF ($SDDK_COMMIT)"
